version: '3.8'
services:
  database:
    container_name: 'prisma-test-database'
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posgres
    ports:
      - $POSTGRES_PORT:5432
